### ISSUE TITLE
Boolean element attributes (disabled, checked, etc.)

### ISSUE THREAD

**Issue by jjt** [jsx/JSX#295]
This is how I've been conditionally putting the `disabled` attribute on elements, with a boolean variable:

``` jsx
<input disabled={isDisabled} type=... />
```

When `disabled` is falsey, the attribute won't be added. When true, it will output the following, which works in browsers but is against the [HTML5 spec](http://www.w3.org/TR/html5/infrastructure.html#boolean-attributes):

``` html
<input disabled="true" type=... />
```

I could get in line with the spec by setting `disabled="disabled"` on the element, but that requires a ternary operation instead of a boolean:

``` jsx
<input disabled={isDisabled ? "disabled" : false} ... />
```

Ideally, my current bit of JSX (at the top of this issue) would output this HTML, assuming `disabled` is set to true:

``` html
<input disabled type=... />
```

**Comment by waldyrious** [comment]
> Hopefully you don't get this too often :p

Unfortunately that's not the case -- see #305.
