### ISSUE TITLE
Making JSX more HTML-like

### ISSUE THREAD

**Issue by jpeg729** [jsx/JSX#343]
I can't just copy-paste some html into my render method without making a few tedious changes...
- `<div class="">` must become `<div className="">`
- `<div multi-word-attribute>` must become `<div multiWordAttribute>`
- `<!-- comment -->` must become `{/* comment */}` or be deleted.
- `<div style="border: 1px solid red">` must become `<div style={{border: '1px solid red'}}>`

The first is necessary because `class` is a js reserved keyword, the second because `multi-word` is a subtraction in js.

BUT jsx _isn't_ javascript - it gets _compiled_ to js. So here are my questions...
1. How hard would it be to detect and transform those cases during compilation?
2. Is it useful/desirable that jsx be different from vanilla html?
3. Would this proposal ease communication with designers, or could it potentially complicate things?

PS. I know there are converters like http://magic.reactjs.net/htmltojsx.htm but that adds an extra step to the process

**Comment by alex-kinokon** [comment]
You are in the [wrong repo](https://github.com/facebook/jsx).
